# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Bingo's Blog
url: http://bingogh.github.io
feed: /atom.xml
author_info: <a href="http://bingogh.github.io/">Bingo</a>

myblog:
  gavatar: images/2.jpg
  gpname: Bingo
  linkedin: https://github.com/bingogh
  github: https://github.com/bingogh
  email: mailto:bingobox@qq.com
  coverimgs: []
  postbgimg: []

categories: [tech, skills]
